apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: NodePort
  selector:
    app: bullseye-backend
  ports:
  - name: broker
    port: 8080
    targetPort: 8080
    protocol: TCP
