apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "bullseye-backend"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: "bullseye-backend"
    spec:
      containers:
      - name: bullseye
        image: {{ .Values.backend.image }}
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: {{ .Release.Name }}-postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: postgres
        - name: DB_USER
          value: {{ .Values.postgres.postgresqlUsername }}
        - name: DB_PASSWORD
          value: {{ .Values.postgres.postgresqlPassword }}
        - name: EC_HOST_API
          value: {{ .Values.ec.url }}{{ .Values.ec.api }}
        - name: EC_HOST_STATIC
          value: {{ .Values.ec.url }}
        - name: EC_HTTP_CLIENT_TIMEOUT_SECONDS
          value: "60"
        - name: EC_PRODUCTS_CATALOG
          value: {{ .Values.ec.site }}
        - name: HW_MQTT_BROKER
          value: "tcp://{{ .Values.mqtt.subdomain }}.{{ .Values.kyma.cluster.hostname }}:31400"
        ports:
        - containerPort: 8080
