apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Release.Name }}-expose-backend
spec:
  service:
    name: {{ .Release.Name }}-backend
    port: 8080
    host: {{ .Values.backend.subdomain }}.{{ .Values.kyma.cluster.hostname }}
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: allow
    - path: /post
      methods: ["POST"]
      accessStrategies:
        - handler: allow
