apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ .Release.Name }}-expose-backend
spec:
    service:
      name: {{ .Release.Name }}-backend
      port: 8080
    hostname: {{ .Values.backend.subdomain }}.{{ .Values.kymaClusterHostname }}
