apiVersion: v1
data:
  config.js: |-
    window.configuration = {
        backendURL: "https://{{ .Values.backend.subdomain }}.{{ .Values.kyma.cluster.hostname }}"
    };
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-config
