apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ .Release.Name }}-expose-front
spec:
    service:
      name: {{ .Release.Name }}-frontend
      port: 80
    hostname: {{ .Values.frontend.subdomain }}.{{ .Values.kymaClusterHostname }}
