apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-mqtt-broker
  ports:
    - name: broker
      port: 1883
      targetPort: 1883
      protocol: TCP
