apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  service:
    name: {{ .Release.Name }}-mqtt-broker
    port: 1883
  hostname: {{ .Values.mqtt.subdomain }}.{{ .Values.kymaClusterHostname }}