apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  gateways:
    - {{ .Release.Name }}-{{ .Values.mqtt.gateway.name}}.{{ .Release.Namespace }}.{{ .Values.kyma.cluster.internal }}
  hosts:
    - {{ .Values.mqtt.subdomain }}.{{ .Values.kyma.cluster.hostname }}
  tcp:
    - match:
        - port: {{ .Values.mqtt.port }}
      route:
        - destination:
            host: {{ .Release.Name }}-mqtt-broker.{{ .Release.Namespace }}.{{ .Values.kyma.cluster.internal }}
            port:
              number: 1883