apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  service:
    name: {{ .Release.Name }}-mqtt-broker
    port: 1883
    host: {{ .Values.mqtt.subdomain }}.{{ .Values.kyma.cluster.hostname }}
  gateway: {{ .Values.kyma.cluster.gateway }}.{{ .Values.kyma.cluster.namespace }}.{{ .Values.kyma.cluster.internal }}
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: allow
    - path: /post
      methods: ["POST"]
      accessStrategies:
        - handler: allow