apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  gateways:
    - {{ .Release.Name }}-gateway.{{ .Release.Namespace }}.svc.cluster.local
  hosts:
    - {{ .Values.mqtt.subdomain }}.{{ .Values.kyma.cluster.hostname }}
  tcp:
    - match:
        - port: 31400
      route:
        - destination:
            host: {{ .Release.Name }}-mqtt-broker.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 1883