apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  gateways:
  - bullseye-gateway.{{ .Release.Name }}.svc.cluster.local
  hosts:
  - {{ .Values.mqtt.subdomain }}.{{ .Values.kymaClusterHostname }}
  tcp:
  - match:
    - port: 31400
    route:
      - destination:
          host: {{ .Release.Name }}-mqtt-broker.{{ .Release.Name }}.svc.cluster.local
          port:
            number: 1883
