apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mqtt-broker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Release.Name }}-mqtt-broker
    spec:
      containers:
        - name: mqtt-broker
          image: {{ .Values.mqtt.image }}
          imagePullPolicy: Always
          restartPolicy: OnFailure
          ports:
            - containerPort: 1883
