apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt
spec:
  type: NodePort
  selector:
    app: bullseye-mqtt
  ports:
    - name: broker
      port: 1883
      targetPort: 1883
      protocol: TCP
