apiVersion: v1
data:
  config.js: |-
    window.configuration = {
        backendURL: 'https://bullseye.34.76.145.96.xip.io'
    };
kind: ConfigMap
metadata:
  creationTimestamp: "2019-08-14T11:11:15Z"
  name: bulls-ui
  namespace: bullseye
  resourceVersion: "386631"
  selfLink: /api/v1/namespaces/bullseye/configmaps/bulls-ui
  uid: 3b73231a-be84-11e9-a20e-42010af001c6
