ec:
  url: "https://localhost:9002"
  api: "/rest/v2"
  site: "electronics"

kyma:
  cluster:
    hostname: "kyma.local"

backend:
  subdomain: "backend"
  image: ""

frontend:
  subdomain: "bullseye"
  image: ""

mqtt:
  subdomain: "mqtt-broker"
  image: ""

postgres:
  postgresqlUsername: "postgres"
  postgresqlPassword: "password"
