version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - EC_HOST_API=https://localhost:9002/rest/v2
      - EC_HOST_STATIC=https://localhost:9002
      - EC_HTTP_CLIENT_TIMEOUT_SECONDS=20
      - HW_MQTT_BROKER=tcp://mqtt-broker:1883
    depends_on:
      - "db"
      - "frontend"
      - "mqtt-broker"
    ports:
      - "8080:8080"
    restart: always
  db:
    image: "postgres:11.5"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
    - devDB01:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    image: "empty"
    ports:
      - "80:80"
  mqtt-broker:
    image: "eclipse-mosquitto"
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
  devDB01:
