version: '3'
services:
  bullseye:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - EC_HOST_API=https://localhost:9002/rest/v2
      - EC_HOST_STATIC=https://localhost:9002
      - EC_HTTP_CLIENT_TIMEOUT_SECONDS=20

      - HW_MQTT_BROKER=tcp://mosquitto:1883
    depends_on:
      - "db"
      - "ui"
      - "mqtt"
    ports:
      - "8080:8080"
  db:
    image: "postgres:11.5"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - devDB01:/var/lib/postgresql/data
  ui:
    image: "empty""
    ports:
      - "80:80"
  mqtt:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
volumes:
  devDB01:
